name: Update KanjiVG SVGs

permissions:
  contents: write

on:
  workflow_call:
    outputs:
        changes:
          description: "If any data changes were made"
          value: ${{ jobs.update.outputs.output1 }}

jobs:
  update:
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.check_changes.outputs.changes }}
      
    steps:
      - name: Checkout branch tip
        uses: actions/checkout@v6
        with:
          ref: 'main'
          fetch-depth: 0
        
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
          
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        
      - name: Run KanjiVG script
        run: python scripts/kanjivg.py
        
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: ${{ steps.check_changes.outputs.changes  == 'true' }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/kanji/
          git commit -m "Update KanjiVG SVGs"
          git push
