name: Monthly Release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  kanjivg:
     uses: ./.github/workflows/kanjivg.yml
  create-release:
    runs-on: ubuntu-latest
    needs: kanjivg
    steps:
      - env:
          KANJIVG: ${{needs.kanjivg.outputs.changes}}
          EXIT: False
        run: echo "$OUTPUT1 $OUTPUT2"
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check For Changes
        id: changes
        if: !$KANJIVG
        run: |
          echo "EXIT=true" >> $GITHUB_ENV

      - name: Get Date
        if: !$EXIT
        run: |
          echo "DATE=$('%d-%m-%y')" >> $GITHUB_ENV
        
      - name: Build Data
        if: !$EXIT
        run: |
          zip -r "kanjicut-data-$DATE.zip" ./data
          
      - name: Create Release
        id: create_release
        if: !$EXIT
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v$DATE'
          release_name: 'v$DATE'
          body: 'Description of the changes in this release'
          
      - name: Upload Release Asset
        id: upload-release-asset 
        if: !$EXIT
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kanjicut-data-all-$DATE.zip
          asset_name: kanjicut-data-all-$DATE.zip
          asset_content_type: application/zip




      
    
