name: Monthly Release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  kanjivg:
     uses: ./.github/workflows/kanjivg.yml

  create-release:
    runs-on: ubuntu-latest
    needs: kanjivg
    steps:  
      - name: Set Proceed to False
        run: |
          echo "PROCEED=false" >> $GITHUB_ENV

      - name: Check For Data Changes
        run: |
          echo "PROCEED=${{ needs.kanjivg.outputs.changes }}" >> $GITHUB_ENV
 
      - name: Checkout
        if: ${{ env.PROCEED }}
        uses: actions/checkout@v4

      - name: Get Date
        if: ${{ env.PROCEED }}
        run: |
          echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        
      - name: Build Data
        if: ${{ env.PROCEED }}
        run: |
          zip -r "kanjicut-data-all.zip" ./data
          
      - name: Create Release
        id: create_release
        if: ${{ env.PROCEED }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ env.DATE }}'
          release_name: 'v${{ env.DATE }}'
          body: 'Monthly automatic KanjiCut data release.'
          
      - name: Upload Release Asset
        id: upload-release-asset 
        if: ${{ env.PROCEED }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kanjicut-data-all.zip
          asset_name: kanjicut-data-all-${{ env.DATE }}.zip
          asset_content_type: application/zip




      
    
