name: Monthly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch KanjiVG Workflow
        uses: codex-/return-dispatch@v2
        id: kanjivg_dispatch
        with:
          repo: kanjicut-data
          owner: kanjicut
          workflow: update-kanjivg-svgs.yml
          
      - name: Await Run ID ${{ steps.kanjivg_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1
        with:
          repo: kanjicut-data
          owner: kanjicut
          run_id: ${{ steps.kanjivg_dispatch.outputs.run_id }}
          poll_interval_ms: 5000

      - name: Compress Data
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./data
          format: zip
          dest: './release'
          destfilename: 'kanjicut-data'

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          automatic_release_tag: "latest"
          files: ./release/kanjicut-data.zip
