name: Monthly Release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  kanjivg:
     uses: ./.github/workflows/kanjivg.yml
  create-release:
    runs-on: ubuntu-latest
    needs: kanjivg
    steps:
      - env:
          KANJIVG: ${{needs.kanjivg.outputs.changes}}
          EXIT: False
        run: echo "$OUTPUT1 $OUTPUT2"
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check For Changes
        id: changes
        if: ${{ !env.KANJIVG }}
        run: |
          echo "env.EXIT=true" >> $GITHUB_OUTPUT
        
        
      - name: Build Data
        if: ${{!env.EXIT}}
        run: |
          zip -r "kanjicut-data-${{ github.run_number }}.zip" ./data
          
      - name: Create Release
        id: create_release
        if: ${{!env.EXIT}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'v${{ github.run_number }}'
          body: 'Description of the changes in this release'
          
      - name: Upload Release Asset
        id: upload-release-asset 
        if: ${{!env.EXIT}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kanjicut-data-${{ github.run_number }}.zip
          asset_name: kanjicut-data-${{ github.run_number }}.zip
          asset_content_type: application/zip




      
    
